-- MySQL Script generated by MySQL Workbench
-- Mon May  2 14:11:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jeronimo_adamo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jeronimo_adamo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jeronimo_adamo` DEFAULT CHARACTER SET utf8 ;
USE `jeronimo_adamo` ;

-- -----------------------------------------------------
-- Table `jeronimo_adamo`.`Days`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeronimo_adamo`.`Days` (
  `idDays` INT NOT NULL AUTO_INCREMENT,
  `date_and_month` DATE NOT NULL,
  PRIMARY KEY (`idDays`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeronimo_adamo`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeronimo_adamo`.`Area` (
  `idArea` INT NOT NULL AUTO_INCREMENT,
  `cardinal_location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeronimo_adamo`.`Concerts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeronimo_adamo`.`Concerts` (
  `idConcerts` INT NOT NULL AUTO_INCREMENT,
  `band` VARCHAR(45) NOT NULL,
  `time_play` TIME NOT NULL,
  `duration` TIME NOT NULL,
  `Days_idDays` INT NOT NULL,
  `Area_idArea` INT NOT NULL,
  PRIMARY KEY (`idConcerts`),
  INDEX `fk_Concerts_Days_idx` (`Days_idDays` ASC) ,
  INDEX `fk_Concerts_Area1_idx` (`Area_idArea` ASC) ,
  CONSTRAINT `fk_Concerts_Days`
    FOREIGN KEY (`Days_idDays`)
    REFERENCES `jeronimo_adamo`.`Days` (`idDays`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Concerts_Area1`
    FOREIGN KEY (`Area_idArea`)
    REFERENCES `jeronimo_adamo`.`Area` (`idArea`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeronimo_adamo`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeronimo_adamo`.`Tickets` (
  `idTickets` INT NOT NULL AUTO_INCREMENT,
  `name_surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `national_id` INT NOT NULL,
  PRIMARY KEY (`idTickets`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeronimo_adamo`.`Tickets_has_Days`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeronimo_adamo`.`Tickets_has_Days` (
  `Tickets_idTickets` INT NOT NULL,
  `Days_idDays` INT NOT NULL,
  PRIMARY KEY (`Tickets_idTickets`, `Days_idDays`),
  INDEX `fk_Tickets_has_Days_Days1_idx` (`Days_idDays` ASC) ,
  INDEX `fk_Tickets_has_Days_Tickets1_idx` (`Tickets_idTickets` ASC),
  CONSTRAINT `fk_Tickets_has_Days_Tickets1`
    FOREIGN KEY (`Tickets_idTickets`)
    REFERENCES `jeronimo_adamo`.`Tickets` (`idTickets`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_has_Days_Days1`
    FOREIGN KEY (`Days_idDays`)
    REFERENCES `jeronimo_adamo`.`Days` (`idDays`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeronimo_adamo`.`Security_Packs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeronimo_adamo`.`Security_Packs` (
  `idSP` INT NOT NULL AUTO_INCREMENT,
  `Area_idArea` INT NOT NULL,
  PRIMARY KEY (`idSP`),
  INDEX `fk_Employee_Area1_idx` (`Area_idArea` ASC),
  CONSTRAINT `fk_Employee_Area1`
    FOREIGN KEY (`Area_idArea`)
    REFERENCES `jeronimo_adamo`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeronimo_adamo`.`Sound_Engenieer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeronimo_adamo`.`Sound_Engenieer` (
  `idSound_Engenieer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Concerts_idConcerts` INT NOT NULL,
  PRIMARY KEY (`idSound_Engenieer`),
  INDEX `fk_Sound_Engenieer_Concerts1_idx` (`Concerts_idConcerts` ASC),
  CONSTRAINT `fk_Sound_Engenieer_Concerts1`
    FOREIGN KEY (`Concerts_idConcerts`)
    REFERENCES `jeronimo_adamo`.`Concerts` (`idConcerts`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeronimo_adamo`.`Toilets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeronimo_adamo`.`Toilets` (
  `idToilets` INT NOT NULL AUTO_INCREMENT,
  `Area_idArea` INT NOT NULL,
  PRIMARY KEY (`idToilets`),
  INDEX `fk_Toilets_Area1_idx` (`Area_idArea` ASC) ,
  CONSTRAINT `fk_Toilets_Area1`
    FOREIGN KEY (`Area_idArea`)
    REFERENCES `jeronimo_adamo`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeronimo_adamo`.`Instruments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeronimo_adamo`.`Instruments` (
  `idInstruments` INT NOT NULL AUTO_INCREMENT,
  `kind` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInstruments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeronimo_adamo`.`Food_Drinks_Stand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeronimo_adamo`.`Food_Drinks_Stand` (
  `idFood_Drinks_Stand` INT NOT NULL AUTO_INCREMENT,
  `Area_idArea` INT NOT NULL,
  PRIMARY KEY (`idFood_Drinks_Stand`),
  INDEX `fk_Food_Drinks_Stand_Area1_idx` (`Area_idArea` ASC),
  CONSTRAINT `fk_Food_Drinks_Stand_Area1`
    FOREIGN KEY (`Area_idArea`)
    REFERENCES `jeronimo_adamo`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeronimo_adamo`.`Merchandise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeronimo_adamo`.`Merchandise` (
  `idMerchandise` INT NOT NULL AUTO_INCREMENT,
  `Area_idArea` INT NOT NULL,
  PRIMARY KEY (`idMerchandise`, `Area_idArea`),
  INDEX `fk_Merchandise_Area1_idx` (`Area_idArea` ASC),
  CONSTRAINT `fk_Merchandise_Area1`
    FOREIGN KEY (`Area_idArea`)
    REFERENCES `jeronimo_adamo`.`Area` (`idArea`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeronimo_adamo`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeronimo_adamo`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Food_Drinks_Stand_idFood_Drinks_Stand` INT NOT NULL,
  `Merchandise_idMerchandise` INT NOT NULL,
  `Merchandise_Area_idArea` INT NOT NULL,
  PRIMARY KEY (`idEmployee`),
  INDEX `fk_Employee_Food_Drinks_Stand1_idx` (`Food_Drinks_Stand_idFood_Drinks_Stand` ASC) ,
  INDEX `fk_Employee_Merchandise1_idx` (`Merchandise_idMerchandise` ASC, `Merchandise_Area_idArea` ASC),
  CONSTRAINT `fk_Employee_Food_Drinks_Stand1`
    FOREIGN KEY (`Food_Drinks_Stand_idFood_Drinks_Stand`)
    REFERENCES `jeronimo_adamo`.`Food_Drinks_Stand` (`idFood_Drinks_Stand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Merchandise1`
    FOREIGN KEY (`Merchandise_idMerchandise` , `Merchandise_Area_idArea`)
    REFERENCES `jeronimo_adamo`.`Merchandise` (`idMerchandise` , `Area_idArea`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeronimo_adamo`.`Dancers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeronimo_adamo`.`Dancers` (
  `idDancers` INT NOT NULL AUTO_INCREMENT,
  `Concerts_idConcerts` INT NOT NULL,
  PRIMARY KEY (`idDancers`),
  INDEX `fk_Dancers_Concerts1_idx` (`Concerts_idConcerts` ASC) ,
  CONSTRAINT `fk_Dancers_Concerts1`
    FOREIGN KEY (`Concerts_idConcerts`)
    REFERENCES `jeronimo_adamo`.`Concerts` (`idConcerts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jeronimo_adamo`.`Concerts_has_Instruments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jeronimo_adamo`.`Concerts_has_Instruments` (
  `Concerts_idConcerts` INT NOT NULL,
  `Instruments_idInstruments` INT NOT NULL,
  PRIMARY KEY (`Concerts_idConcerts`, `Instruments_idInstruments`),
  INDEX `fk_Concerts_has_Instruments_Instruments1_idx` (`Instruments_idInstruments` ASC),
  INDEX `fk_Concerts_has_Instruments_Concerts1_idx` (`Concerts_idConcerts` ASC),
  CONSTRAINT `fk_Concerts_has_Instruments_Concerts1`
    FOREIGN KEY (`Concerts_idConcerts`)
    REFERENCES `jeronimo_adamo`.`Concerts` (`idConcerts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Concerts_has_Instruments_Instruments1`
    FOREIGN KEY (`Instruments_idInstruments`)
    REFERENCES `jeronimo_adamo`.`Instruments` (`idInstruments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
